# This file contains the workflow that'll build and deploy the Neural Needledrop database.
name: Neural Needledrop Database

# This Workflow will only run on changes to the database code.
on:
  push:
    branches:
      - main
    paths:
      - "database/**"

jobs:
  # This job will deploy the database!
  build-and-deploy-database:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GAR
        uses: docker/login-action@v3
        with:
          registry: us-central1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCP_KEY }}
      - name: Install SSH client
        run: sudo apt-get install openssh-client
      - name: SSH and Update Server
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          GCP_KEY: ${{secrets.GCP_KEY}}
          OPENAI_API_KEY: ${{secrets.OPENAI_API_KEY}}
          IP_ADDRESS: 35.193.127.52
        run: |

          # Setting up SSH keys
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $IP_ADDRESS >> ~/.ssh/known_hosts

          # Create a temporary file to store the GCP JSON key
          echo "$GCP_KEY" > gcp_key.json

          # DO THE REST OF THE DATABASE DEPLOYMENT
