# This file contains the workflow that'll build and deploy the Neural Needledrop ui.
name: Neural Needledrop UI

# This Workflow will only run on changes to the ui code.
on:
  push:
    branches:
      - main
    paths:
      - "ui/**"

jobs:
  # This job will deploy the ui!
  build-and-deploy-ui:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GAR
        uses: docker/login-action@v3
        with:
          registry: us-central1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCP_KEY }}
      - name: Build and push ui image
        uses: docker/build-push-action@v5.1.0
        with:
          context: ui
          tags: us-central1-docker.pkg.dev/neural-needledrop/neural-needledrop-webapp/neural-needledrop-ui:latest
          provenance: false
          platforms: linux/amd64
          push: true
      - name: Install SSH client
        run: sudo apt-get install openssh-client
      - name: SSH and Update Server
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          IP_ADDRESS: ${{secrets.COMPUTE_ENGINE_IP}}
        run: |

          # Setting up SSH keys
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $IP_ADDRESS >> ~/.ssh/known_hosts

          # Create a temporary file to store the GCP JSON key
          echo "$GCP_KEY" > gcp_key.json

          # Copy the deployment script to the server, along with the GCP key
          scp -i ~/.ssh/id_rsa ./ui/deployment/deploy_ui.sh trevormhubbard@$IP_ADDRESS:/tmp/deploy_ui.sh
          scp -i ~/.ssh/id_rsa ./gcp_key.json trevormhubbard@$IP_ADDRESS:/tmp/gcp_key.json

          # Deleting the GCP key from the local machine
          rm gcp_key.json

          # Running the deployment script on the server
          ssh -i ~/.ssh/id_rsa trevormhubbard@$IP_ADDRESS 'chmod +x /tmp/deploy_ui.sh && GCP_KEY=/tmp/gcp_key.json bash /tmp/deploy_ui.sh'
